### ISSUE TITLE
CPPUNIT mot installed => mo tests

### ISSUE THREAD

**Issue by urmatt** [PlayWithIt/TFStubserver#1]
I got this message although I have cppunit on my Linux.

**Comment by PlayWithIt** [comment]
The makefile looks for

> /usr/include/cppunit/extensions/HelperM*

is this installed on your system?
Do you have the cppunit devel package installed or just the library?

**Comment by wechsler42** [comment]
On Ubuntu 16.04 LTS I installed the packages libcppunit-doc and libcppunit-dev but unfortunately "CPPUNIT not installed => no tests" is still showing up at the end of the compilation process with "make".  The file "/usr/include/cppunit/extensions/HelperMacros.h" is in place, although I cannot find it with "locate". Are there any more hints?

**Comment by PlayWithIt** [comment]
The makefile looked into a relative location, I changed that, should compile with tests now

**Comment by PlayWithIt** [comment]
I was confused: this part has no tests.
Since this is just a sub-project of my tinkerforge projects, tests are located in other projects.
I just removed the message about missing CPPUNIT
