### ISSUE TITLE
support for "bricklet_industrial_dual_analog_in_v2"

### ISSUE THREAD

**Issue by RandDruid** [PlayWithIt/TFStubserver#4]
First of all, thank you for the cool project. I have to develop software for the customer who is using Tinkerforge hardware, but I don't have any myself.

I need to simulate relatively new sensor "bricklet_industrial_dual_analog_in_v2", which is not (yet) in your project.
I tried to add it myself, by coping corresponding *.c and *.h files from latest Tinkerforge download into /src/bindings/ folder.
In general project compiles and enumeration through connected sensors works (3 in my test), but when I try to subscribe for value changes using callback, I got error "Function ID 15 is not supported".
Can you give some tips where to look to complete integration of this device? I can create pull request later on.
Or may it would be more easy for you to update project with new sensors yourself.

Thanks!

**Comment by PlayWithIt** [comment]
Hi,

the starting point for new emulated devices is "SimulatedDevice::setupFunctions()".
There is a case for each DEVICE_IDENTIFIER.

The old device is implemented:


    case INDUSTRIAL_DUAL_ANALOG_IN_DEVICE_IDENTIFIER:
        functions = new DeviceDualAnalogIn(createValueProvider("valueProvider1"), createValueProvider("valueProvider2"));
        break;

This can be used a a copy.

I'll have a look at the weekend, maybe this goes quickly.

Kind regards

Holger

> First of all, thank you for the cool project. I have to develop software for the customer who is using Tinkerforge hardware, but I don't have any myself.
>
> I need to simulate relatively new sensor "bricklet_industrial_dual_analog_in_v2", which is not (yet) in your project.
> I tried to add it myself, by coping corresponding *.c and *.h files from latest Tinkerforge download into /src/bindings/ folder.
> In general project compiles and enumeration through connected sensors works (3 in my test), but when I try to subscribe for value changes using callback, I got error "Function ID 15 is not supported".
> Can you give some tips where to look to complete integration of this device? I can create pull request later on.
> Or may it would be more easy for you to update project with new sensors yourself.
>
> Thanks!
>
>

**Comment by PlayWithIt** [comment]
I added support for industrial dual analog in V2 in stubserver and stub UI, hope that works ..

**Comment by RandDruid** [comment]
Sorry for delay, I checked sensor, it works perfect. Thank you!
